Code refactoring
lean-delivery/ansible-role-solr-hybris-config pull request #9
Opened 2019-05-01 18:36 UTC by ViachaslauKabak

Role refactored

2019-05-03 08:09 UTC, tgadiev requested changes

2019-05-03 08:09 UTC, tgadiev commented on README.md
> +[![Galaxy](https://img.shields.io/badge/galaxy-lean__delivery.solr-hybris-config-blue.svg)](https://galaxy.ansible.com/lean_delivery/solr-hybris-config)
```suggestion
[![Galaxy](https://img.shields.io/badge/galaxy-lean__delivery.solr__hybris__config-blue.svg)](https://galaxy.ansible.com/lean_delivery/solr_hybris_config)
```

2019-05-03 08:09 UTC, tgadiev commented on README.md
>    - **Supported OS**:
Debian?

2019-05-03 08:09 UTC, tgadiev commented on molecule/cloud-aws-direct/molecule.yml
> +#    - idempotence
Why?

2019-05-03 08:09 UTC, tgadiev commented on molecule/cloud-aws-direct/playbook.yml
> +      transport: openjdk-fallback
Why do we need this variable in playbook and in inventory at the same time?

2019-05-03 08:09 UTC, tgadiev commented on molecule/cloud-aws-windows/molecule.yml
> +#    - idempotence
Why?

2019-05-03 08:09 UTC, tgadiev commented on molecule/cloud-aws-windows/molecule.yml
> +    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
Not needed for AWS

2019-05-03 08:09 UTC, tgadiev commented on tasks/main.yml
> +    - 'system/not-supported.yml'
Is that variable?

2019-05-03 08:09 UTC, tgadiev commented on tasks/system/Linux.yml
> +- name: 'Install pip package'
These pre-requisites should be moved to pre_tasks or to prepare stage. It's not scope of hybris-config role to install boto.

2019-05-03 08:09 UTC, tgadiev commented on tasks/system/Linux.yml
> +- name: Install boto module
These pre-requisites should be moved to pre_tasks or to prepare stage. It's not scope of hybris-config role to install boto.

2019-05-03 08:09 UTC, tgadiev commented on tasks/system/Linux.yml
> +- name: Install data hybris components
May be combine to one task with previous?

2019-05-03 08:09 UTC, tgadiev commented on tasks/system/Windows.yml
> +- name: Upload data hybris components
May be combine to one task with previous?

2019-05-03 08:09 UTC, tgadiev commented on tasks/system/Windows.yml
> +- name: Install data hybris components
May be combine to one task with previous?

2019-05-04 07:05 UTC, ViachaslauKabak commented on README.md
>    - **Supported OS**:
done

2019-05-04 11:04 UTC, tgadiev requested changes

2019-05-04 11:04 UTC, tgadiev commented on tasks/system/Windows.yml
> +- name: Create contrib temporary directory
Why separate task?

2019-05-04 11:04 UTC, tgadiev commented on molecule/cloud-aws-windows/molecule.yml
> +    assign_public_ip: False
```suggestion
    assign_public_ip: True
```

2019-05-04 11:04 UTC, tgadiev commented on molecule/cloud-aws-windows/molecule.yml
> +    vpc_subnet_id: subnet-05a2ef2b767afec50
```suggestion
    vpc_subnet_id: subnet-01be2149
```

2019-05-04 12:02 UTC, ViachaslauKabak commented on tasks/system/Windows.yml
> +- name: Create contrib temporary directory
not to harden the role

2019-05-04 12:49 UTC, tgadiev approved these changes

2019-05-04 12:50 UTC, merged